### ISSUE TITLE
Canal youtube

### ISSUE THREAD

**Issue by lucianobarauna** [riocss/riocss#10]
Pensei nisso para colocarmos os streams o que vocês acham ?
@Lucasktrindade  @MathMesquita  @afonsopacifer

**Comment by Lucasktrindade** [comment]
Sim, mas fazer hangouts também é interessante

**Comment by lucianobarauna** [comment]
Sim!
Vou fechar aqui então pq o canal está criado

**Comment by afonsopacifer** [comment]
Vamos gravar, fazer live, ou algo assim durante o evento?

Posso levar camera + Tripe + microfones... eu fiz transmissão ao vivo do último Meetup de CSS SP e ficou bom.. tbm fizemos uma live no meu canal batendo papo antes do evento..

Live de bate papo
https://www.youtube.com/watch?v=aJtJHhw72YE&t

Live do evento
https://www.youtube.com/watch?v=7XSFSs2Tx_w&t

Se for gravar.. posso ajudar a editar etc...

E claro.. meu canal está a disposição para o que precisarem

**Comment by MathMesquita** [comment]
### ótima ideia

**Comment by lucianobarauna** [comment]
Boa ideia e vlw.

Podemos fazer o primeiro evento só com a palestrar e com o temp colocar os vídeos. 

Tenho medo de colocarmos muita coisa no começo e não conseguirmos manter, seria bom colocar aos poucos até por quê temos que nos acostumar com esse ritmo.

**Comment by Lucasktrindade** [comment]
Então, eu tenho pouca experiência com isso de live e tal. Mas na Stone tem o WiFi disponível para fazer isso, e próximo do palco tem um cabo ethernet que já tem uma qualidade maior. Podemos tentar fazer lá, só peço que chegue uns 30 minutos antes que te ajudo a fazer isso.

**Comment by lucianobarauna** [comment]
Bom vou fechar aqui então porquê o @afonsopacifer fez um vídeo no canal dele falando do evento e se manter assim vai ser ótimo ;-)
Se tivermos necessidade reabrimos então a issue
