### ISSUE TITLE
Sobre o twitter

### ISSUE THREAD

**Issue by afonsopacifer** [riocss/riocss#12]
Pessoal, vi que o twitter ta bem ativo, muito massa <3

Acho que podemos deixar o user do twitter em mais evidência, assim como o user do meetup. Podemos passar a adicionar os "links" nas artes p divulgação etc....

Não sei se o Maujor divulgou, mas vou pedir p ele divulgar as paradas, e alguns amigos tbm p dar um gás... 

Enfim... parabéns p quem ta mexendo na conta <3

**Comment by MathMesquita** [comment]
Importante, divulgar os links das midias !!

**Comment by lucianobarauna** [comment]
Vlw @afonsopacifer eu como fico com aba no tweetdeck acabei colocando a do rio.css hehe
Na próxima arte eu coloco o nosso twitter e o meetup ;-)
Ele só curtiu no meu face rs e nada no twitter pelo o que lembro
E @MathMesquita  e @Lucasktrindade usem também a conta do rio css no twitter rs
