### ISSUE TITLE
Página facebook e não grupo

### ISSUE THREAD

**Issue by lucianobarauna** [riocss/riocss#15]
Galera acho que seria uma parada interessante termos pelo menos uma página para centralizarmos nossas fotos dos eventos e também termos pelo menos uma presença mínima no facebook para nos divulgarmos mais.
Seria isso mesmo só uma página sem grupo de discussão, afinal nós temos o telegram para isso e sem mais de um lugar para discussões se não ficamos doidos.

Esquema de postagens podemos linkar o twitter do rio.css para as postagens aparecerem lá ;-) então nem vamos ter taaaaannnto trampo assim.

Eu tinha pensado nisso antes mais dispensei e trocando ideia com um amigo me voltou isso a cabeça, agora eu cheguei a comentar isso como vocês sobre essa abordagem ?

O que acham ?

**Comment by afonsopacifer** [comment]
Acho massa.. principalmente não ser um grupo.. mas não acho o facebook o melhor lugar para subir as fotos.. talvez subir as fotos no próprio Meetup e linkar na página no FB.. não sei.... 

PS: mandei um [PR p começarmos a organizar](https://github.com/riocss/riocss/pull/16) isso alias :), como fotos e links.

**Comment by lucianobarauna** [comment]
Pensando...
Hum..separaria então as coisas então deixando só a página do meetup com foco no eventon colocando ali as fotos deixando só o facebook para anunciar e linkar a galera para a página do meetup.
É acho ok
@Lucasktrindade e @MathMesquita  o que acham ?

**Comment by lucianobarauna** [comment]
Bom criei a página e subi as fotos para nosso repositório do Github, Drive, Facebook e Meetup. :-)
