### ISSUE TITLE
Ajuste no logo & Formatos logo

### ISSUE THREAD

**Issue by lucianobarauna** [riocss/riocss#2]
Ajustar logotipo colocando o CSS em maiúsculo
- Criar png em alta qualidade
- Criar svg

**Comment by Lucasktrindade** [comment]
Disponibiliza em algum lugar assim que possível

**Comment by lucianobarauna** [comment]
Vou colocar aqui mesmo, assim podemos ter um repositório fixo e quem quiser pega daqui. Não acha melhor ?

**Comment by Lucasktrindade** [comment]
Sim, pode ser aqui mesmo no repo

**Comment by lucianobarauna** [comment]
Logo ajustado e criei uma pasta para colocarmos nossos artefatos rs
Segue o caminho e commit https://github.com/riocss/riocss/commit/8da5c44016eddd8e3f3724403af38196c20cece1
Podemos fechar a issue
