### ISSUE TITLE
Criar email do grupo no gmail

### ISSUE THREAD

**Issue by lucianobarauna** [riocss/riocss#3]
Criar gmail do riocss

**Comment by Lucasktrindade** [comment]
Vou criar como riocss@gmail.com

**Comment by Lucasktrindade** [comment]
Já existe, criei como riocssorg@gmail.com

**Comment by Lucasktrindade** [comment]
As credenciais estão na pasta compartilhada

**Comment by lucianobarauna** [comment]
Cria um drive nesse gmail e compartilha com geral ;-)
