### ISSUE TITLE
Meettup css - Colocar email do grupo

### ISSUE THREAD

**Issue by lucianobarauna** [riocss/riocss#4]
O grupo foi criado no meu email pessoal.
Quando for criado o novo email devemos ver a possibilidade de alterar para esse email ou teremos que excluir esse grupo e criar um novo com esse email central

**Comment by Lucasktrindade** [comment]
É uma boa, podemos fazer isso. Mas acho que não tem problema em ser nosso porque se não teremos que tirar a confirmação toda vez kkkkkkk

**Comment by lucianobarauna** [comment]
Blz então não fazemos essa alteração
