### ISSUE TITLE
Criar adesivo :-)

### ISSUE THREAD

**Issue by lucianobarauna** [riocss/riocss#6]
Lista para checar fornecedores [preços, prazo, etc]
- https://www.nerdstickers.com.br/loja/

**Comment by Lucasktrindade** [comment]
Já temos como vai ser o Sticker?

**Comment by lucianobarauna** [comment]
Vai ser o logo.
Quando eu matar a issue do logo eu mato isso ;-)

**Comment by lucianobarauna** [comment]
Adesivo criado e add: https://github.com/riocss/riocss/commit/44c8a219857178b5132c49353004e647806e9360

**Comment by lucianobarauna** [comment]
Vou fechar aqui galera ;-)
