### ISSUE TITLE
Criar Medium

### ISSUE THREAD

**Issue by MathMesquita** [riocss/riocss#8]
Como definido na #1 vamos criar um medium para o riocss, porém como pretendemos dar acesso as demais comunidades de frontend do rio, creio que o melhor nome para o medium seria frontendrio não riocss....

o que acham?

**Comment by lucianobarauna** [comment]
Sim mais se liga.
Eu hoje estava pensando numa coisa nós temos que ver se as outras também vão querer participar.
Talvez poderíamos criar a riocss e depois ver com as outras sobre isso. No ruim pelo menos vamos ter a nossa o que acham ?

**Comment by lucianobarauna** [comment]
Já foi feito ?

**Comment by MathMesquita** [comment]
Desculpa demora,

Acho válido a gente criar a do geral e a nossa, e depois chamar a galera...

**Comment by lucianobarauna** [comment]
Vou fechar aqui. Se resolvermos criaro medium reabrimos.
Falo isso pq podemos criar um site estático e fazer como blog se for o caso
